{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* Default value. *}
<div class="block">
    <label>{'Default value'|i18n( 'design/standard/class/datatype' )}:</label>
    <select name="ContentClass_ezevent_default_{$class_attribute.id}">
    <option value="0" {if eq( $class_attribute.data_int1, 0 )}selected="selected"{/if}>{'Empty'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="1" {if eq( $class_attribute.data_int1, 1 )}selected="selected"{/if}>{'Current datetime'|i18n( 'design/standard/class/datatype' )}</option>
    <option value="2" {if eq( $class_attribute.data_int1, 2 )}selected="selected"{/if}>{'Adjusted current datetime'|i18n( 'design/standard/class/datatype' )}</option>
    </select>
</div>

{* Custom default value. *}
<div class="block">
<fieldset>
    <legend>{'Current date and time adjusted by'|i18n( 'design/standard/class/datatype' )}</legend>

    <div class="block">
    {* Year. *}
    <div class="element">
        <label>{'Year'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezevent_year_{$class_attribute.id}" size="5" value="{if $class_attribute.content.year}{$class_attribute.content.year}{/if}" />
    </div>

    {* Month. *}
    <div class="element">
        <label>{'Month'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezevent_month_{$class_attribute.id}" size="3" value="{if  $class_attribute.content.month}{$class_attribute.content.month}{/if}" />
    </div>

    {* Day. *}
    <div class="element">
        <label>{'Day'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezevent_day_{$class_attribute.id}" size="3" value="{if $class_attribute.content.day}{$class_attribute.content.day}{/if}" />
        &nbsp;
        &nbsp;
        &nbsp;
    </div>

    {* Hour. *}
    <div class="element">
        <label>{'Hour'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezevent_hour_{$class_attribute.id}" size="3" value="{if $class_attribute.content.hour}{$class_attribute.content.hour}{/if}" />
    </div>

    {* Minute. *}
    <div class="element">
        <label>{'Minute'|i18n( 'design/standard/class/datatype' )}:</label>
        <input type="text" name="ContentClass_ezevent_minute_{$class_attribute.id}" size="3" value="{if $class_attribute.content.minute}{$class_attribute.content.minute}{/if}" />
    </div>

    <div class="break"></div>

</div>
</fieldset>
</div>
